// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class CollectionData : IData
{
    public int ID => item_id;

    public int item_id;
    public string Name;
    public int MaxStack;
    public int zeroInt;
    public float zeroFloat;
    public string sampleString;
    public string Desc;
    public bool sampleBool;
}

[Serializable]
public class CollectionDataTable
{
    public List<CollectionData> collectiondata;
}
