// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class EnemyData : IData
{
    public int ID => enemy_id;

    public int enemy_id;
    public string name;
    public int max_hp;
    public int attack_power;
    public float Patrol_speed;
    public float Chase_speed;
    public float Detect_Range;
    public int[] skill_set;
    public int[] Exskill_set;
}

[Serializable]
public class EnemyDataTable
{
    public List<EnemyData> enemydata;
}
