// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class EnemySkillData : IData
{
    public int ID => skill_id;

    public int skill_id;
    public string name;
    public int Damage;
    public int Damage2;
    public int Damage3;
    public int HealAmount;
    public float Cooldown;
    public float Range;
    public string Desc;
}

[Serializable]
public class EnemySkillDataTable
{
    public List<EnemySkillData> enemyskilldata;
}
