// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class PlayerData
{
    public int max_hp;
    public int attack_power;
    public int attack_power2;
    public int attack_power3;
    public float jumpforce;
    public int skill_ids;
    public float speed;
}
