// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class PlayerData
{
    public int Max_Hp;
    public int Attack_Power;
    public int Attack_Power2;
    public int Attack_Power3;
    public float Jumpforce;
    public int Skill_Ids;
    public float Speed;
}
