// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class PlayerData
{
    public int MaxHealth;
    public int MaxStamina;
    public int SpecialAttackStamina;
    public int DodgeStamina;
    public float DodgeInvincibleTime;
    public int DoubleJumpStamina;
    public int ParryStamina;
    public float ParryInvincibleTime;
    public int ParryDamage;
    public int WallJumpStamina;
    public float InvincibleTime;
    public int[] NormalAttackDamage;
    public int JumpAttackDamage;
    public int DownAttackDamage;
    public float Jumpforce;
    public int Skill_Ids;
    public float Speed;
}
