// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SampleSingleData
{
    public int sampleInt;
    public float sampleFloat;
    public int zeroInt;
    public float zeroFloat;
    public string sampleString;
    public string zeroString;
    public bool sampleBool;
    public int[] intArray;
    public string[] stringArray;
    public float[] floatArray;
    public bool[] boolArray;
}
