// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SkillData : IData
{
    public int ID => skill_id;

    public int skill_id;
    public string name;
    public int Damage;
    public int Damage2;
    public int DmgUp;
    public float Delay;
    public float Recovery;
    public int Stamina;
    public int Cooldown;
    public int Duration;
    public int HealAmount;
    public int MaxStack;
    public string Desc;
}

[Serializable]
public class SkillDataTable
{
    public List<SkillData> skilldata;
}
