// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SkillData : IData
{
    public int ID => skill_id;

    public int skill_id;
    public string name;
    public string Damage;
    public string Delay;
    public string Column1;
    public string Dec;
}

[Serializable]
public class SkillDataTable
{
    public List<SkillData> skilldata;
}
