// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SoundData : IData
{
    public int ID => Sound_id;

    public int Sound_id;
    public string name;
    public bool Loop;
    public string Desc;
}

[Serializable]
public class SoundDataTable
{
    public List<SoundData> sounddata;
}
