// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class StageData : IData
{
    public int ID => Stage_id;

    public int Stage_id;
    public int[] Monster_id;
    public string[] Boss_name;
    public string Boss_path;
    public string Map_path;
    public float Time_limit;
    public float[] BossPhaseThresholds;
}

[Serializable]
public class StageDataTable
{
    public List<StageData> stagedata;
}
